addSbtPlugin("pl.project13.scala" % "sbt-jmh" % "0.3.7")
addSbtPlugin("com.geirsson" % "sbt-ci-release" % "1.4.31")
addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.3.0")
addSbtPlugin("com.47deg" % "sbt-microsites" % "1.0.2")
addSbtPlugin("org.scalameta" % "sbt-mdoc" % "2.1.0")
addSbtPlugin("io.spray" % "sbt-boilerplate" % "0.6.1")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat" % "0.1.9")
