addSbtPlugin("pl.project13.scala" % "sbt-jmh" % "0.3.7")
addSbtPlugin("com.geirsson" % "sbt-ci-release" % "1.2.6")
addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.2.1")
addSbtPlugin("com.47deg"  % "sbt-microsites" % "0.9.7")
addSbtPlugin("org.scalameta" % "sbt-mdoc" % "2.0.0" )
