addSbtPlugin("pl.project13.scala" % "sbt-jmh" % "0.3.7")
addSbtPlugin("com.geirsson" % "sbt-ci-release" % "1.4.31")
addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.2.1")
addSbtPlugin("com.47deg" % "sbt-microsites" % "1.0.0")
addSbtPlugin("org.scalameta" % "sbt-mdoc" % "2.0.3")
addSbtPlugin("io.spray" % "sbt-boilerplate" % "0.6.1")
addSbtPlugin("org.lyranthe.sbt" % "partial-unification" % "1.1.2")
